package org.example.hakerbot.entity;

public enum State {
    START,

    AWAITING_NAME,
    AWAITING_LASTNAME,
    AWAITING_MIDDLENAME,
    AWAITING_BIRTHDATE,

    CHOOSE_GAME,

    SPACE_START,
    SPACE_AWAITING_RADAR,
    SPACE_AWAITING_SHIELD,
    SPACE_CHOOSE_PATH,
    SPACE_AWAITING_CALCULATION,

    HACKER_START,
    HACKER_AWAITING_SCAN,
    HACKER_AWAITING_CONNECT,
    HACKER_CHOOSE_TARGET,
    HACKER_AWAITING_MATH_ANSWER
}
